// Mock data cho các loại văn khấn
export interface Prayer {
  id: string;
  title: string;
  category: string;
  description: string;
  occasion: string;
  difficulty: "Dễ" | "Trung bình" | "Khó";
  duration: string;
  content: string[];
  preparation: string[];
  notes: string[];
  relatedFestivals?: string[]; // IDs của các ngày lễ liên quan
}

export const prayersData: Record<string, Prayer[]> = {
  featured: [
    {
      id: "van-khan-cau-tu",
      title: "Văn khấn cầu tự (cầu con)",
      category: "cau-tu",
      description:
        "Văn khấn cầu tự, cầu con trai hoặc con gái, cầu con hiền lành, đủ duyên sinh nở.",
      occasion: "Khi vợ chồng cầu con, khấn cầu tự",
      difficulty: "Khó",
      duration: "15-20 phút",
      preparation: [
        "13 tờ tiền (tiền giấy để cúng)",
        "13 loại quả khác nhau",
        "13 loại đồ chơi trẻ con",
        "Hương, hoa",
        "Chuẩn bị sớ trạng cầu tự (nếu có)",
      ],
      notes: [
        "Sau khi lễ, mỗi lần lễ xong nên lấy về 1 thứ trong mâm lễ (theo hướng dẫn cuối bài)",
        "Nếu đi đò, mua thêm một suất đò; nếu vào quán ăn, mua thêm một suất ăn cho ‘con’",
        "Khấn rõ cầu con trai hoặc con gái tùy tâm",
      ],
      content: [
        "Nam mô A Di Đà Phật!",
        "Con lạy 9 phương trời, lạy 10 phương Phật, Chư Phật 10 phương.",
        "Con lạy Thiên Quan – Linh thần nơi bản địa ở khu vực này.",
        "",
        "Đệ tử con là ………………………………………… sinh ngày…………………………....",
        "Cùng chồng/vợ ………………………………………. sinh ngày…………………………..",
        "Ngụ tại:……………………………………………………………………………………....",
        "",
        "Hôm nay nhân ngày lành tháng tốt, khí tiết năm ……… bầu trời cao vút tỏa sáng phúc lành. Vợ chồng con thành tâm thiết lễ cùng dâng sớ trạng kính lạy Trung thiên mệnh chủ, Bắc Cực Tử vi, Ngọc Đế Thiên quân bệ hạ, giáng trần soi xét cho hạnh phúc gia đình con được có con trai/con gái, hạnh phúc xum vầy truyền vào hậu thế.",
        "",
        "Con lạy Nhật cung Thái Dương, Nguyệt cung Thái Âm, Đông phương Thanh đế, Bắc phương Hắc đế, Tây phương Bạch đế, kính cáo tôn thần, chư vị các Thần linh giáng trần soi xét chữ cương thường đạo lý vợ chồng cho vợ chồng con được cửa rộng nhà cao, tiền của dồi dào, có con trai/con gái thông minh, học hành chăm chỉ, một niềm kính thiện.",
        "",
        "Con lạy quan Nam Tào Bắc Đẩu, Thái Bạch Thái Tuế, Văn Xương, Văn Khúc, Nhị thập bát tú Ngũ hành tinh quân.",
        "Trước án liệt vị linh quân tôn thần Tản Viên Đại Thánh, Trần triều Hưng Đạo Quốc Tảng Đại Vương cùng Tiên Phật Thánh Thần, Quan Âm Bồ tát chí đức tôn linh hiển thành thần thông, tiết độ cho con được có con trai/con gái để trọn vẹn hiếu sinh, hạnh phúc gia đình trong ấm ngoài êm, để ông bà, chồng vợ chân tình thương yêu chăm sóc.",
        "",
        "Làm điều thiện được âm dương báo đáp, cây trái thêm hoa sinh sôi nảy nở.",
        "",
        "Trước án liệt vị các linh quân tôn thần xa thôi lại theo gần xin giải trừ vận hạn, tiêu trừ yêu ma tai ách làm muộn đường con trai/con gái.",
        "",
        "Chúng con người trần nhục nhãn nan chi, việc trần thế chưa tường, việc âm chưa tỏ. Thân sinh nơi trần tục mệnh bởi cung trời, cầu xin Thần Phật đức độ cao dầy, hạ trần giáng thế cho con điều thiện, cho con hạnh phúc có con trai/con gái, có của, vượng đinh như vượng tài, để trên gánh việc Thánh, dưới gánh việc trần, phúc địa đãi phúc nhân, gia đình hai dòng họ vui chữ Nghi Gia truyền vào hậu thế.",
        "",
        "Gia đình chúng con bút son thêm số, sổ ngọc thêm năm vượng đinh vượng tài, thêm người thêm của. Hạnh phúc của gia đình dòng họ cùng cuộc đời chúng con lại như nước tràn đầy chảy đến. Một nhà vui vẻ, oanh yến đậm đà, đào hồng thắm biếc.",
        "",
        "Vậy xin yết cáo tôn thần cùng dâng sớ trạng CẦU TỰ, xin tỏ tấc thành giáng ban trăm phúc.",
        "",
        "Trăm lạy các tôn linh, cúi nhờ ơn đức.",
        "Sở nguyện thành tâm, con xin cảm tạ.",
        "Vạn vọng bách bái Thần Phật mười phương, ban ơn phúc dầy cho chúng con được toại nguyện đường con cái.",
      ],
    },
    {
      id: "ram-thang-bay-chung-sinh",
      title: "Văn khấn chúng sinh (cô hồn) ngày Rằm tháng Bảy",
      category: "chung-sinh",
      description: "Văn khấn cúng chúng sinh, cô hồn không nơi nương tựa ngày Rằm tháng Bảy.",
      occasion: "Rằm tháng Bảy (Xá tội vong nhân) – cúng chúng sinh ngoài trời",
      difficulty: "Khó",
      duration: "15-20 phút",
      preparation: [
        "Lễ cúng ngoài trời: mâm cháo loãng, bỏng, ngô, khoai, bánh kẹo…",
        "Gạo, muối (rắc bốn phương tám hướng)",
        "Tiền vàng, quần áo chúng sinh",
        "Hương, đèn"
      ],
      notes: [
        "Đặt mâm lễ ngoài sân, trước cửa nhà, không cúng trên bàn thờ gia tiên",
        "Sau khi cúng, rắc gạo muối ra ngoài đường, không mang lễ vào nhà",
        "Tránh trẻ con tranh giành đồ cúng khi chưa hóa vàng, kết lễ"
      ],
      relatedFestivals: ["nguyen-tieu"],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "Con lạy Đức Phật Di Đà.",
        "Con lạy Bồ Tát Quan Âm.",
        "Con lạy Táo Phủ Thần quân Chinh thần.",
        "",
        "Tiết tháng 7 sắp thu phân,",
        "Ngày rằm xá tội vong nhân hải hà.",
        "",
        "Âm cung mở cửa ngục ra,",
        "Vong linh không cửa không nhà,",
        "Đại Thánh Khảo giáo – A Nan Đà Tôn giả,",
        "Tiếp chúng sinh không mả, không mồ bốn phương,",
        "Gốc cây xó chợ đầu đường,",
        "Không nơi nương tựa, đêm ngày lang thang.",
        "",
        "Quanh năm đói rét cơ hàn,",
        "Không manh áo mỏng che làn heo may.",
        "",
        "Cô hồn năm bắc đông tây,",
        "Trẻ già trai gái về đây hợp đoàn.",
        "",
        "Dù rằng chết uổng, chết oan,",
        "Chết vì nghiện hút, chết tham làm giàu,",
        "Chết tai nạn, chết ốm đau,",
        "Chết đâm chết chém, chết đánh nhau tiền tình,",
        "Chết bom đạn, chết đao binh,",
        "Chết vì chó dại, chết đuối, chết vì sinh sản giống nòi,",
        "Chết vì sét đánh giữa trời…",
        "",
        "Nay nghe tín chủ thỉnh mời,",
        "Lai lâm nhận hưởng mọi lời trước sau.",
        "",
        "Cơm canh cháo nẻ trầu cau,",
        "Tiền vàng quần áo đủ màu đỏ xanh,",
        "Gạo muối quả thực hoa đăng,",
        "Mang theo một chút để dành ngày mai.",
        "",
        "Phù hộ tín chủ lộc tài,",
        "An khang thịnh vượng, hòa hài gia trung.",
        "",
        "Nhớ ngày xá tội vong nhân,",
        "Lại về tín chủ thành tâm thỉnh mời.",
        "",
        "Bây giờ nhận hưởng xong rồi,",
        "Dắt nhau già trẻ về nơi âm phần.",
        "",
        "Tín chủ thiêu hóa kim ngân,",
        "Cùng với quần áo đã được phân chia.",
        "",
        "Kính cáo Tôn thần,",
        "Chứng minh công đức,",
        "Cho tín chủ con:",
        "Tên là:....................................",
        "Vợ/Chồng:..............................",
        "Con trai:.................................",
        "Con gái:..................................",
        "Ngụ tại:...................................",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!"
      ]
    },
  ],
  tet: [
    {
      id: "tat-nien-30-tet",
      title: "Bài khấn 30 Tết tại gia - Lễ Tất Niên",
      category: "tet",
      description:
        "Văn khấn cúng tất niên chiều 30 Tết, truy niệm tổ tiên và cáo tuế",
      occasion: "Chiều 30 Tết",
      difficulty: "Dễ",
      duration: "10-15 phút",
      content: [
        "Cẩn cáo gia tiên ngày Tết.",
        "Con nam mô a di đà phật (3 lần).",
        "Con lạy 9 phương trời 10 phương phật chư phật 10 phương.",
        "Con lạy gia tiên nội ngoại bà cô ông mãnh họ ( Xưng họ gia đình)",
        "",
        "Việt Nam Quốc",
        "Thành phố… / Tỉnh...",
        "Quận... / Huyện...",
        "Phường… / Xã...",
        "Đường… / Thôn xóm...",
        "Nhà số...",
        "",
        "Con xin kính cẩn thưa rằng:",
        "Vật đời xa vời",
        "Năm cùng tháng kiệt",
        "Xuân tiết gần sang",
        "Đông tàn sắp hết",
        "Chiều 30 Tết sửa lễ tất niên",
        "Truy niệm tổ tiên",
        "Theo như thường lệ",
        "Tửu trà cáo tuế",
        "Lễ bạc kính dâng",
        "Phủ tiếu hương đăng",
        "Lễ nghi thịnh soạn",
        "",
        "Lạy xin tổ tiên chứng giám lòng thành, lai lâm hiến hưởng 3 ngày tết",
        "Phù hộ độ trì toàn gia quyến già trẻ gái trai họ...",
        "Bình yên khang khái muôn phần tốt tươi",
        "",
        "Đọc bài khấn từ đầu đến cuối 3 lần",
        "Rồi a di đà phật. (1 lần)",
        "Sau đó vái 3 vái",
      ],
      preparation: [
        "Hoa, quả (lễ mặn tùy tâm)",
        "Thắp hương các bát 3 nén",
        "Một ngọn nến hoặc thắp đèn dầu",
      ],
      notes: [
        "Gần hết hương thì lên hương vòng",
        "Đến giao thừa, lễ ngoài trời xong, thắp mỗi bát trong nhà 5 nén để đón cung sinh vào nhà",
        "Cần xưng họ gia đình và địa chỉ cụ thể",
        "Đọc bài khấn 3 lần từ đầu đến cuối",
      ],
    },
    {
      id: "tet-doan-ngo-gia-tien",
      title: "Văn khấn ngày Tết Đoan Ngọ (Mùng 5 tháng 5 âm lịch)",
      category: "doan-ngo",
      description:
        "Văn khấn gia tiên ngày Tết Đoan Ngọ, còn gọi là ngày giết sâu bọ.",
      occasion: "Mùng 5 tháng 5 âm lịch (Tết Đoan Ngọ)",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      preparation: [
        "Hương, hoa, vàng mã",
        "Nước sạch",
        "Rượu nếp",
        "Các loại hoa quả: mận, hồng xiêm, dưa hấu, vải, chuối…",
      ],
      notes: [
        "Theo tục xưa, buổi sáng có tục ăn rượu nếp, hoa quả để ‘giết sâu bọ’",
        "Có thể cúng vào buổi sáng hoặc giờ Ngọ",
        "Điền rõ tên tín chủ và địa chỉ",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Hoàng thiên Hậu Thổ chư vị Tôn thần.",
        "- Con kính lạy ngài Bản cảnh Thành hoàng, ngài Bản xứ Thổ địa, ngài Bản gia Táo quân cùng chư vị Tôn thần.",
        "- Con kính lạy Tổ tiên, Hiển khảo, Hiển tỷ, chư vị Hương linh (nếu bố, mẹ còn sống thì thay bằng Tổ khảo, Tổ Tỷ).",
        "",
        "Tín chủ chúng con là:…………",
        "Ngụ tại:…………………………..",
        "",
        "Hôm nay là ngày Đoan Ngọ, chúng con sửa sang hương đăng, sắm sanh lễ vật, hoa đăng, trà quả dâng lên trước án.",
        "",
        "Chúng con kính mời ngài Bản cảnh Thành hoàng, Chư vị Đại Vương, ngài Bản xứ Thần linh Thổ địa, ngài Bản gia Táo quân, Ngũ phương, Long Mạch, Tài thần, cúi xin các Ngài giáng lâm trước án chứng giám lòng thành, thụ hưởng lễ vật.",
        "",
        "Chúng con kính mời các cụ Tổ Khảo, Tổ Tỷ, chư vị Hương linh gia tiên nội ngoại họ....................., cúi xin các vị thương xót con cháu chứng giám tâm thành, thụ hưởng lễ vật.",
        "",
        "Tín chủ con lại kính mời các vị Tiền chủ, Hậu chủ tại nhà này, đất này đồng lâm án tiền, đồng lai hâm hưởng, độ cho chúng con thân cung khang thái, bản mệnh bình an, bốn mùa không hạn ách, tám tiết hưởng bình an thịnh vượng.",
        "",
        "Chúng con lễ bạc tâm thành, trước án kính lễ, cúi xin được phù hộ độ trì.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
    {
      id: "tet-han-thuc-gia-tien",
      title: "Văn khấn Tết Hàn Thực (Mùng 3 tháng 3)",
      category: "han-thuc",
      description:
        "Văn khấn gia tiên ngày Tết Hàn Thực, thường cúng bánh trôi, bánh chay.",
      occasion: "Mùng 3 tháng 3 âm lịch (Tết Hàn Thực)",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      preparation: [
        "Hương, hoa, trầu cau",
        "Bánh trôi (3 hoặc 5 bát)",
        "Bánh chay (3 hoặc 5 bát)",
      ],
      notes: [
        "Theo tục Việt, vẫn có thể nấu nướng bình thường",
        "Văn khấn dùng khi cúng gia tiên tại nhà",
        "Điền đủ tên tín chủ, địa chỉ, ngày tháng năm",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Hoàng thiên Hậu Thổ chư vị Tôn thần.",
        "- Con kính lạy ngài Bản cảnh Thành hoàng, ngài Bản xứ Thổ địa, ngài Bản gia Táo quân cùng chư vị Tôn thần.",
        "- Con kính lạy Cao Tằng Tổ khảo, Cao Tằng Tổ Tỷ, Thúc Bá, Đệ Huynh, Cô Di, Tỷ Muội họ nội họ ngoại.",
        "",
        "Tín chủ (chúng) con là:...........",
        "Ngụ tại:………………………",
        "",
        "Hôm nay là ngày……………………….. gặp tiết Hàn Thực, tín chủ chúng con cảm nghĩ thâm ân trời đất, chư vị Tôn thần, nhớ đức cù lao Tiên tổ, thành tâm sắm lễ, quả cau lá trầu, hương hoa trà quả, đốt nén tâm hương, dâng lên trước án.",
        "",
        "Chúng con kính mời ngài Bản cảnh Thành hoàng Chư vị Đại Vương, ngài bản xứ Thần linh Thổ địa, ngài Bản gia Táo quân, Ngũ phương, Long Mạch, Tài thần giáng lâm trước án chứng giám lòng thành, thụ hưởng lễ vật.",
        "",
        "Chúng con kính mời các cụ Tổ Khảo, Tổ Tỷ, chư vị Hương linh gia tiên nội ngoại họ....................., cúi xin thương xót con cháu giáng về linh chứng giám tâm thành, thụ hưởng lễ vật.",
        "",
        "Tín chủ con lại kính mời các vị vong linh các vị Tiền chủ, Hậu chủ ngụ trong nhà này, đất này đồng lâm án tiền, đồng lai hâm hưởng, phù hộ cho toàn gia chúng con luôn luôn mạnh khoẻ, mọi sự bình an, vạn sự tốt lành, gia đình hoà thuận, trên bảo dưới nghe.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
  ],
  ram: [
    {
      id: "mong-mot-ram",
      title: "Văn khấn ngày mồng một và ngày rằm hàng tháng",
      category: "ram",
      description:
        "Văn khấn cúng Gia Thần, Gia Tiên vào ngày Mồng Một (lễ Sóc) và Rằm (lễ Vọng)",
      occasion: "Mồng 1 và Rằm hàng tháng",
      difficulty: "Dễ",
      duration: "10-15 phút",
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười Phương Chư Phật, Chư phật mười phương.",
        "- Con kính lạy Hoàng thiên, Hậu Thổ chư vi Tôn thần.",
        "- Con kính lạy ngài Đông Thần quân",
        "- Con kính lạy ngài Bản gia thổ địa Long Mạch",
        "- Con kính lạy các ngài Ngũ phương, Ngũ thổ, Phúc đức Tôn thần",
        "- Con kính lạy ngài tiền hậu địa chủ tài thần",
        "- Con kính lạy các Tôn thần cai quản trong khu vực này.",
        "",
        "Tín chủ (chúng) con là:............................................",
        "Ngụ tại:....................................................................",
        "",
        "Hôm nay là ngày...... tháng...... năm...., tín chủ con thành tâm sửa biện hương hoa lễ vật, kim ngân trà quả đốt nén hương thơm dâng lên trước án.",
        "",
        "Chúng con thành tâm kính mời: ngài Kim Niên đương cai Thái Tuế chí đức Tôn thần, ngài Bản cảnh Thành hoàng Chư vị Đại Vương, ngài Đông trù Tư mệnh Táo phủ Thần quân, ngài Bản gia Thổ địa. Long Mạch Tôn thần, các ngài Ngũ Phương, Ngũ Thổ, Phúc đức chính thần, các vị Tôn thần cai quản trong khu vực này.",
        "",
        "Cúi xin các Ngài nghe thấu lời mời thương xót thương tín chủ giáng lâm trước án, chứng giám lòng thành, thụ hưởng lễ vật, phù trì tín chủ chúng con toàn gia an lạc công việc hanh thông. Người người được bình an, lộc tài tăng tiến, tâm đạo mở mang, sở cầu tất ứng, sở nguyện tòng tâm.",
        "",
        "Chúng con lễ bạc tâm thành, trước án kính lễ, cúi xin được phù hộ độ trì.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật",
        "Nam mô a di Đà Phật!",
      ],
      preparation: [
        "Lễ chay: Hương, hoa, trầu cau, quả, tiền vàng",
        "Có thể cúng thêm lễ mặn: Rượu, thịt gà luộc, các món mặn",
        "Lễ vật tối giản: Hương, hoa, lá trầu, quả cau, chén nước",
      ],
      notes: [
        "Lễ Sóc: Cúng vào ngày Mồng Một hàng tháng",
        "Lễ Vọng: Cúng vào chiều tối ngày Rằm hàng tháng",
        "Lễ vật có thể rất giản dị, quan trọng là thành tâm kính lễ",
        "Cầu xin cho gia đình được khỏe mạnh, bình an, may mắn, thành đạt",
        "Cần điền tên tín chủ, địa chỉ và ngày tháng năm cụ thể",
      ],
    },
    {
      id: "tet-trung-thu-gia-tien",
      title: "Văn cúng tổ tiên ngày Tết Trung Thu",
      category: "trung-thu",
      description:
        "Văn khấn cúng gia tiên nhân ngày Tết Trung Thu (Rằm tháng Tám âm lịch).",
      occasion: "Rằm tháng 8 (Tết Trung Thu)",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      preparation: [
        "Bánh nướng, bánh dẻo",
        "Cốm, chuối, na, hồng, bưởi…",
        "Hương, hoa",
        "Đèn, nến",
        "Các lễ vật hoa quả truyền thống khác tùy tâm",
      ],
      notes: [
        "Thường cúng buổi tối, khi trăng đã lên cao",
        "Có thể kết hợp bày mâm cỗ trông trăng cho trẻ nhỏ",
        "Điền đầy đủ tên tín chủ và địa chỉ trước khi khấn",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Hoàng thiên Hậu Thổ chư vị Tôn thần.",
        "- Con kính lạy ngài Bản cảnh Thành hoàng, ngài Bản xứ Thổ địa, ngài Bản gia Táo quân cùng chư vị Tôn thần.",
        "- Con kính lạy Cao Tằng Tổ khảo, Cao Tằng Tổ Tỷ, Thúc Bá, Đệ Huynh, Cô Di, Tỷ Muội họ nội họ ngoại.",
        "",
        "Tín chủ (chúng) con là:..........................",
        "Ngụ tại:………………………..",
        "",
        "Hôm nay là ngày Rằm tháng Tám, gặp tiết Trung Thu, tín chủ chúng con thành tâm sắm lễ, hương hoa trà quả, thắp nén tâm hương dâng lên trước án.",
        "",
        "Chúng con kính mời ngài Bản cảnh Thành hoàng Chư vị Đại Vương, ngài Bản xứ Thần linh Thổ địa, ngài Bản gia Táo quân, Ngũ phương, Long Mạch, Tài Thần. Cúi xin các ngài giáng lâm trước án chứng giám lòng thành, thụ hưởng lễ vật.",
        "",
        "Chúng con kính mời các cụ Tổ Khảo, Tổ Tỷ, chư vị Hương linh gia tiên nội ngoại họ.................., cúi xin thương xót con cháu linh thiêng hiện về, chứng giám tâm thành, thụ hưởng lễ vật.",
        "",
        "Tín chủ con lại kính mời các vị Tiền chủ, Hậu chủ ngụ tại nhà này, đất này, đồng lâm án tiền, đồng lai hâm hưởng. Xin các ngài độ cho chúng con thân cung khang thái, bản mệnh bình an. Bốn mùa không hạn ách, tám tiết hưởng vinh quang thịnh vượng.",
        "",
        "Chúng con lễ bạc tâm thành, trước án kính lễ, cúi xin được phù hộ độ trì.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
    {
      id: "ram-thang-bay-gia-tien",
      title: "Văn khấn lễ tổ tiên ngày Rằm tháng Bảy (Vu Lan - Trung Nguyên)",
      category: "trung-nguyen",
      description:
        "Văn khấn cúng Tổ tiên ngày Rằm tháng Bảy tại nhà nhân tiết Vu Lan – Trung Nguyên.",
      occasion: "Rằm tháng 7 âm lịch (Vu Lan - Trung Nguyên)",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      preparation: [
        "Hương, hoa",
        "Rượu, xôi",
        "Mâm cơm mặn cúng gia tiên (tùy tâm, chuẩn bị chu đáo)",
        "Vàng mã, quần áo, hài giấy…",
      ],
      notes: [
        "Thường cúng gia tiên trong nhà trước, sau mới cúng chúng sinh ngoài sân",
        "Điền rõ họ tên tín chủ, địa chỉ, năm âm lịch",
        "Có thể kết hợp làm lễ cầu siêu, phóng sinh tùy tín tâm",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư vị Phật, Chư Phật mười phương.",
        "- Con kính lạy Tổ tiên nội ngoại và chư vị Hương linh.",
        "",
        "Tín chủ (chúng) con là:....................................",
        "Ngụ tại:...............................................................",
        "",
        "Hôm nay là ngày Rằm tháng Bảy năm ............. nhân gặp tiết Vu Lan vào dịp Trung Nguyên, chúng con nhớ đến Tổ tiên ông bà cha mẹ đã sinh thành ra chúng con, gây dựng cơ nghiệp, xây đắp nền nhân, khiến nay chúng con được hưởng âm đức.",
        "",
        "Chúng con cảm nghĩ ơn đức cù lao khôn báo, cảm công trời biển khó đền, nên tín chủ con sửa sang lễ vật, hương hoa, trà quả, kim ngân, vàng bạc, thắp nén tâm hương, thành tâm kính lên các cụ Cao Tằng Tổ Khảo, Cao Tằng Tổ Tỷ, Bá Thúc, Đệ Huynh, Cô Di, Tỷ Muội và tất cả hương hồn trong nội tộc, ngoại tộc của họ.............",
        "",
        "Cúi xin các vị thương xót cháu con, linh thiêng hiện về, chứng giám lòng thành, thụ hưởng lễ vật, phù hộ cho con cháu mạnh khoẻ bình an, lộc tài vượng tiến, vạn sự tốt lành, gia đạo hưng long, hướng về chính giáo.",
        "",
        "Chúng con lễ bạc tâm thành, trước án kính lễ, cúi xin được phù hộ độ trì.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
    {
      id: "ram-thang-gieng-nguyen-tieu",
      title: "Văn khấn Tết Nguyên Tiêu (Rằm tháng Giêng)",
      category: "nguyen-tieu",
      description:
        "Văn khấn gia tiên, Thổ Công, Táo quân nhân ngày Rằm tháng Giêng – lễ Thượng Nguyên.",
      occasion: "Rằm tháng Giêng âm lịch",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      preparation: [
        "Mâm lễ chay cúng Phật (nếu có bàn thờ Phật)",
        "Mâm cúng gia tiên: cơm mặn ngày Tết đầy đủ, tinh khiết",
        "Hương, hoa, vàng mã",
        "Đèn nến, trầu cau, rượu",
      ],
      notes: [
        "Dân gian có câu: “Lễ Phật quanh năm không bằng ngày Rằm tháng Giêng”",
        "Có thể lập đàn tràng tại gia để cầu an, giải hạn",
        "Nên cúng vào buổi tối hoặc chiều tối ngày Rằm",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Hoàng thiên Hậu Thổ chư vị Tôn thần.",
        "- Con kính lạy ngài Bản cảnh Thành Hoàng, ngài Bản xứ Thổ địa, ngài Bản gia Táo quân cùng chư vị Tôn thần.",
        "- Con kính lạy Cao Tằng Tổ Khảo, Cao Tằng Tổ Tỷ, Thúc Bá Đệ Huynh, Cô Di, Tỷ Muội họ nội họ ngoại.",
        "",
        "Tín chủ (chúng) con là: ...............................................",
        "Ngụ tại:........................................................................",
        "",
        "Hôm nay là ngày Rằm tháng Giêng năm... gặp tiết Nguyên tiêu, tín chủ con lòng thành, sửa sang hương đăng, sắm sanh lễ vật, dâng lên trước án.",
        "",
        "Chúng con kính mời ngài Bản cảnh Thành hoàng chư vị Đại Vương, ngài Bản xứ Thần linh Thổ địa, ngài Bản gia Táo quân, Ngũ phương, Long Mạch, Tài Thần. Cúi xin các ngài linh thiêng nghe thấu lời mời, giáng lâm trước án, chứng giám lòng thành thụ hưởng lễ vật.",
        "",
        "Chúng con kính mời các các cụ Tổ Khảo, Tổ Tỷ, chư vị Hương linh gia tiên nội ngoại họ................... nghe lời khẩn cầu, kính mời của con cháu, giáng về chứng giám tâm thành, thụ hưởng lễ vật.",
        "",
        "Tín chủ con lại kính mời Ông bà Tiền chủ, Hậu chủ về hưởng lễ vật, chứng giám lòng thành, phù hộ độ trì cho gia chung chúng con được vạn sự tốt lành, bốn mùa không hạn ách, tám tiết hưởng an bình.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
    {
      id: "ram-gieng-dang-sao-giai-han",
      title: "Văn khấn cúng dâng sao giải hạn (Rằm tháng Giêng)",
      category: "giai-han",
      description:
        "Văn khấn dâng sao giải hạn, nghinh sao tốt, giải sao xấu nhân ngày Rằm tháng Giêng.",
      occasion: "Rằm tháng Giêng (cúng sao giải hạn hoặc nghinh sao)",
      difficulty: "Khó",
      duration: "15-20 phút",
      preparation: [
        "Lập đàn ngoài trời hoặc trong nhà tùy điều kiện",
        "Hương, hoa, trầu cau",
        "Lễ chay: hoa quả, trà nước",
        "Đèn, nến theo số lượng và màu sắc tương ứng từng sao",
        "Bài vị sao trên giấy màu tương ứng ngũ hành của sao",
      ],
      notes: [
        "Cần xem mình được sao nào chiếu mệnh trong năm để sắm lễ đúng quy cách",
        "Rằm tháng Giêng thường là lần cúng quan trọng nhất trong năm",
        "Nên giữ tâm thanh tịnh, tránh sát sinh trong ngày cúng sao",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "Hôm nay là ngày Rằm tháng Giêng năm...................",
        "Tín chủ (chúng) con là:..............................................",
        "Ngụ tại:…………………………………..",
        "",
        "Chúng con thành tâm có lời kính mời:",
        "Nhật cung Thái Dương Thiên Tử tinh quân,",
        "Nam Tào Bắc Đẩu tinh quân,",
        "Thái Bạch, Thái Tuế tinh quân,",
        "Bắc Cực Tử vi Đại Đức tinh quân,",
        "Văn Xương Văn Khúc tinh quân,",
        "Nhị thập Bát Tú, Ngũ Hành tinh quân,",
        "La Hầu, Kế Đô tinh quân.",
        "",
        "Giáng lâm trước án, nghe lời mời cẩn tấu:",
        "Ngày Rằm Nguyên Tiêu, theo lệ trần tục, tín chủ con thành tâm sắm lễ, quả cau lá trầu, hương hoa trà quả, thắp nén tâm hương dâng lên trước án, kính mời các vị lai lâm hâm hưởng, phù hộ cho toàn gia chúng con luôn luôn mạnh khoẻ, mọi sự bình an, vạn sự tốt lành, gia đình hoà thuận, trên bảo dưới nghe.",
        "",
        "Đèn trời sán lạn,",
        "Chiếu thắp cõi trần.",
        "Xin các tinh quân,",
        "Lưu ân lưu phúc.",
        "Lễ tuy mọn bạc,",
        "Lòng thành có dư.",
        "Mệnh vị an cư,",
        "Thân cung khang thái.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
  ],
  "gia-tien": [
    {
      id: "gio-thuong-gia-tien-cat-ky",
      title: "Văn khấn Gia tiên ngày Giỗ Thường (Cát Kỵ)",
      category: "gio-thuong",
      description:
        "Văn khấn gia tiên ngày Giỗ Thường (Cát Kỵ) – giỗ từ năm thứ ba trở đi.",
      occasion: "Ngày giỗ thường (Cát Kỵ) từ năm thứ ba sau khi mất",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      preparation: [
        "Hương, hoa, quả, phẩm oản",
        "Mâm cơm mặn: xôi, gà, các món cơm canh",
        "Vàng mã, trầu rượu…",
      ],
      notes: [
        "Thường trong phạm vi gia đình, họ tộc, không mời khách quá rộng",
        "Có thể làm lễ Tiên Thường (cáo giỗ) trước một ngày",
        "Khi khấn thay đổi xưng hô: Hiển khảo, Hiển tỷ, Tổ khảo, Tổ tỷ… cho đúng",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Đức Hoàng Thiên Hậu Thổ chư vị Tôn thần.",
        "- Con kính lạy ngài Đông Trù Tư mệnh Táo phủ Thần Quân.",
        "- Con kính lạy các ngài Thần linh, Thổ địa cai quản trong xứ này.",
        "- Con kính lạy Tổ Tiên nội ngoại họ………………………………………………….",
        "",
        "Tín chủ (chúng) con là……………………………………………………………………",
        "Ngụ tại………………………………………………………………………………….",
        "",
        "Hôm nay là ngày …………… tháng …………… năm………………………………",
        "Là chính ngày Cát Kỵ của…………………………………………………………………",
        "",
        "Thiết nghĩ…………………. vắng xa trần thế, không thấy âm dung.",
        "Năm qua tháng lại ngày húy lâm. Ơn võng cực xem bằng trời biển, nghĩa sinh thành không lúc nào quên.",
        "Càng nhớ công ơn gây cơ tạo nghiệp bao nhiêu, càng cảm thâm tình, không bề dãi tỏ.",
        "",
        "Nhân ngày Cát Kỵ, hôm nay chúng con và toàn gia con cháu thành tâm sắm lễ, quả cau, lá trầu, hương hoa trà quả, thắp nén tâm hương dâng lên trước án, thành khẩn kính mời………………………………………………………………………",
        "",
        "Mất ngày……………..tháng………………….năm……………………………………..",
        "Mộ phần táng tại…………………………………………………………………………..",
        "",
        "Cúi xin linh thiêng giáng về linh sàng, chứng giám lòng thành, thụ hưởng lễ vật, độ cho con cháu an ninh khang thái, vạn sự tốt lành, gia cảnh hưng long thịnh vượng.",
        "",
        "Con lại xin kính mời các vị Tổ Tiên nội ngoại, Tổ Khảo, Tổ Tỷ, Bá Thúc, Huynh Đệ, Cô Di, Tỷ Muội và toàn thể các Hương linh gia tiên đồng lai hâm hưởng.",
        "Tín chủ con lại xin kính mời ngài Thổ Công, Táo Quân và chư vị Linh thần đồng lai giám cách thượng hưởng.",
        "Tín chủ lại mời các vị vong linh Tiền chủ, Hậu chủ nhà này, đất này cùng tới hâm hưởng.",
        "",
        "Chúng con lễ bạc tâm thành, cúi xin được phù hộ độ trì.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
    {
      id: "gio-het-dai-tuong",
      title: "Văn khấn chính ngày Giỗ Hết (Đại Tường)",
      category: "gio-het",
      description:
        "Văn khấn chính ngày Giỗ Hết (Đại Tường) – sau 2 năm 3 tháng, đánh dấu hết tang.",
      occasion: "Ngày Giỗ Hết (Đại Tường) – 2 năm 3 tháng sau ngày mất",
      difficulty: "Khó",
      duration: "15-20 phút",
      preparation: [
        "Hương, hoa, phẩm oản",
        "Mâm cơm mặn tươm tất: xôi, gà, thịt, tôm, cua…",
        "Vàng mã, đồ mã (quần áo, nhà cửa… tùy tập tục)",
        "Có thể kết hợp lễ Cải cát, sang mộ sau đó",
      ],
      notes: [
        "Giỗ Hết là mốc quan trọng: bỏ tang, trở lại sinh hoạt bình thường",
        "Sau Giỗ Hết thường chọn ngày tốt cải táng (cải cát) nếu có điều kiện",
        "Nên xưng đúng danh xưng người mất: Hiển khảo, Hiển tỷ, Tổ khảo, Tổ tỷ…",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Đức Đương cảnh Thành hoàng chư vị Đại Vương.",
        "- Con kính lạy ngài Đông Trù Tư mệnh Táo phủ Thần Quân.",
        "- Con kính lạy các ngài Thần linh, Thổ địa cai quản trong xứ này.",
        "- Con kính lạy chư gia tiên Cao Tằng Tổ Khảo, Cao Tằng Tổ Tỷ, Tổ Tiên nội ngoại họ…………………………………………………………………………………………",
        "",
        "Tín chủ (chúng) con là:……………………………………………………………………",
        "Ngụ tại:…………………………………………………………………………………….",
        "",
        "Hôm nay là ngày ……………….. tháng ……………... năm ……………………………",
        "Chính ngày Giỗ Hết của……………………………………………………………………",
        "",
        "Thiết nghĩ……………… vắng xa trần thế, không thấy âm dung. Năm qua tháng lại vừa ngày Giỗ Hết. Ơn võng cực xem bằng trời biển, nghĩa sinh thành không lúc nào quên.",
        "Càng nhớ công ơn gây cơ tạo nghiệp bao nhiêu, càng cảm thâm tình, không bề dãi tỏ.",
        "",
        "Nhân ngày chính giỗ, chúng con và toàn gia con cháu, nhất tâm sắm sửa lễ vật kính dâng, đốt nén tâm hương dãi tỏ tấc thành.",
        "",
        "Thành khẩn kính mời………………………………………………………………………",
        "Mất ngày…………. Tháng……………… năm……………………………………………",
        "Mộ phần táng tại:…………………………………………………………………………..",
        "",
        "Cúi xin linh thiêng giáng về linh sàng, chứng giám lòng thành, thụ hưởng lễ vật, độ cho con cháu bình an, gia cảnh hưng long thịnh vượng.",
        "",
        "Tín chủ lại mời vong linh các vị Tiền chủ, Hậu chủ trong đất này cùng tới hâm hưởng.",
        "Tín chủ con lại xin kính mời các cụ Tổ Tiên nội ngoại, Tổ Khảo, Tổ Tỷ, Bá Thúc, Huynh Đệ, Cô Di, Tỷ Muội và toàn thể các Hương linh gia tiên đồng lai hâm hưởng.",
        "",
        "Chúng con lễ bạc tâm thành, cúi xin được phù hộ độ trì.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
    {
      id: "gio-dau-tieu-tuong",
      title: "Văn khấn chính ngày Giỗ Đầu (Tiểu Tường)",
      category: "gio-dau",
      description:
        "Văn khấn chính ngày Giỗ Đầu – giỗ đầu tiên sau một năm ngày mất.",
      occasion: "Giỗ Đầu (Tiểu Tường) – đúng một năm ngày mất",
      difficulty: "Khó",
      duration: "15-20 phút",
      preparation: [
        "Hương, hoa, phẩm oản",
        "Mâm cơm mặn tươm tất",
        "Vàng mã và đồ mã dâng cúng (tiền vàng, quần áo giấy, hình nhân nếu theo tục)",
        "Lễ vật thường nhiều, linh đình hơn các giỗ sau",
      ],
      notes: [
        "Giỗ Đầu vẫn thuộc vòng tang, không khí còn bi ai, sầu thảm",
        "Thường có thêm đồ mã gọi là ‘mã biếu’ cho các thần linh",
        "Có thể thuê kèn trống nếu gia đình theo tục lệ cũ",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Đức Đương cảnh Thành hoàng chư vị Đại Vương.",
        "- Con kính lạy ngài Đông Trù Tư mệnh Táo phủ Thần Quân.",
        "- Con kính lạy các ngài Thần linh, Thổ địa cai quản trong xứ này.",
        "- Con kính lạy chư gia tiên Cao Tằng Tổ Tiên nội ngoại họ………………………………",
        "",
        "Tín chủ (chúng) con là:……………………………………………………………………",
        "Ngụ tại:…………………………………………………………………………………….",
        "",
        "Hôm nay là ngày …………... tháng ………..….. năm ……………………………………",
        "Chính ngày Giỗ Đầu của……………………………………………………………………",
        "",
        "Năm qua tháng lại, vừa ngày húy lâm. Ơn võng cực xem bằng trời biển, nghĩa sinh thành không lúc nào quên.",
        "Càng nhớ công ơn gây cơ tạo nghiệp bao nhiêu, càng cảm thâm tình, không bề dãi tỏ.",
        "",
        "Nhân ngày chính giỗ, chúng con và toàn gia con cháu, nhất tâm sắm sửa lễ vật kính dâng, đốt nén tâm hương dãi tỏ tấc thành.",
        "",
        "Thành khẩn kính mời………………………………………………………………………",
        "Mất ngày…………. Tháng……………… năm……………………………………………",
        "Mộ phần táng tại:…………………………………………………………………………..",
        "",
        "Cúi xin linh thiêng giáng về linh sàng, chứng giám lòng thành, thụ hưởng lễ vật, độ cho con cháu bình an, gia cảnh hưng long thịnh vượng.",
        "",
        "Tín chủ con lại xin kính mời các cụ Tổ Tiên nội ngoại, Tổ Khảo, Tổ Tỷ, Bá Thúc, Cô Di và toàn thể các Hương linh gia tiên đồng lai hâm hưởng.",
        "Tín chủ lại mời vong linh các vị Tiền chủ, Hậu chủ trong đất này cùng tới hâm hưởng.",
        "",
        "Chúng con lễ bạc tâm thành, cúi xin được phù hộ độ trì.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
    {
      id: "le-thiet-linh",
      title: "Văn khấn lễ Thiết Linh",
      category: "tang-le",
      description: "Văn khấn lễ Thiết Linh – lập bàn thờ tang, đặt linh vị sau khi có người mất.",
      occasion: "Ngay sau khi lập bàn thờ tang, đặt linh vị người mới mất",
      difficulty: "Khó",
      duration: "10-15 phút",
      preparation: [
        "Bàn thờ tang riêng (nếu có)",
        "Linh vị, ảnh, bát hương cho người mới mất",
        "Hương, hoa, trầu cau, rượu, nước",
        "Đèn, nến, đồ lễ chay/mặn tùy gia đình"
      ],
      notes: [
        "Thường do con trai trưởng hoặc cháu đích tôn chủ lễ",
        "Đọc ngay sau khi thiết lập xong bàn thờ tang",
        "Xưng hô đúng ‘Hiển… chân linh’"
      ],
      content: [
        "Nam mô A Di Đà Phật!",
        "Nam mô A Di Đà Phật!",
        "Nam mô A Di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Đức Đương cảnh Thành hoàng chư vị Đại vương.",
        "- Con kính lạy ngài Đông Trù Tư mệnh Táo phủ.",
        "- Con kính lạy chư gia tiên Cao Tằng Tổ Khảo, Cao Tằng Tổ Tỷ họ………….",
        "",
        "Hôm nay là ngày...... tháng...... năm .........................",
        "Con trai trưởng (hoặc cháu đích tôn) là......... ................ vâng theo lệnh mẫu thân (hoặc phụ thân) và các chú bác, cùng với anh rể, chị gái và các em trai gái, dâu rể, con cháu nội ngoại kính lạy.",
        "",
        "Nay nhân ngày lễ Thiết Linh theo nghi lễ cổ truyền, kính dâng lễ mọn biểu lộ lòng thành.",
        "",
        "Trước linh vị của: Hiển................ chân linh.",
        "Xin kính cẩn trình thưa rằng:",
        "",
        "Than ôi!",
        "Gió thổi nhà Thung, mây che núi Hỗ (nếu khóc cha) hoặc núi Dĩ (nếu khóc mẹ).",
        "Dung mạo một mai vắng vẻ, bão xô cây, nghĩ lại ngậm ngùi thay.",
        "Âm dương đôi ngả xa vời, mây phủ núi, trông càng đau đớn nhẽ!",
        "",
        "Sương bay chớp nhoáng, bạch vân nghi ngút, cõi phù sinh;",
        "Nến đỏ hương thơm, án toạ hắt hiu đồ sự tử.",
        "Vài tuần nghi tiết, mong anh hồn thấu khúc tình văn;",
        "Tấc dạ bi hoài, trông linh vị, tuôn dòng ai lệ!",
        "",
        "Ôi! Thương ôi!!",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!"
      ]
    },
    {
      id: "le-thanh-phuc",
      title: "Văn khấn lễ Thành Phục",
      category: "tang-le",
      description: "Văn khấn lễ Thành Phục – sau khi gia quyến mặc đồ tang, đứng trước linh cữu.",
      occasion: "Lễ Thành Phục trong đám tang (sau khi mặc tang phục)",
      difficulty: "Khó",
      duration: "10-15 phút",
      preparation: [
        "Tang phục cho con cháu, gia quyến",
        "Bàn thờ tang đã lập, linh cữu đã an vị",
        "Hương, hoa, lễ vật đơn sơ"
      ],
      notes: [
        "Thường vẫn do trưởng nam hoặc cháu đích tôn chủ lễ",
        "Đọc sau lễ Thiết Linh, khi mọi người đã mặc tang phục",
        "Có thể thêm lời bi cảm phù hợp hoàn cảnh"
      ],
      content: [
        "Nam mô A Di Đà Phật!",
        "Nam mô A Di Đà Phật!",
        "Nam mô A Di Đà Phật!",
        "",
        "- Con lạy chín phương trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Đức Đương cảnh Thành hoàng chư vị Đại Vương.",
        "- Con kính lạy ngài Đông Trù Tư mệnh Táo phủ Thần quân.",
        "- Con kính lạy chư gia tiên Cao Tằng Tổ Khảo, Cao Tằng Tổ Tỷ.",
        "",
        "Hôm nay là ngày....... tháng........ năm .....................",
        "Con trai trưởng (hoặc cháu đích tôn) là........................... vâng theo lệnh của mẫu thân (hoặc phụ thân) và các chú bác, cùng với anh rể, chị gái và các em trai gái, dâu rể, con cháu nội ngoại kính lạy.",
        "",
        "Nay nhân ngày Lễ Thành Phục theo nghi lễ cổ truyền, kính dâng lễ mọn biểu lộ lòng thành.",
        "",
        "Trước linh vị của: Hiển....................... chân linh, xin kính cẩn trình thưa rằng:",
        "",
        "Than ôi! Núi Hỗ (hoặc núi Dĩ) mây che,",
        "Chồi Thung (hoặc Huyên) gió bẻ.",
        "Cõi trăm năm, trời khéo hẹp hòi thay;",
        "Cơ một phút, đời sao mau mắn nhẽ!",
        "",
        "Sân Lai tử, những mong ngày tháng rộng,",
        "Bõ công ơn áo nặng cơm dày!",
        "Đồ Thôi y, đâu đã lạ lùng thay, càng cám cảnh đầu tang tóc chế…",
        "",
        "Trời đất làm chi cực thế!",
        "Chạnh nhớ cha/mẹ điều ăn nết ở, tấm lòng sầu chín khúc, rồi năm canh.",
        "Ai xui nên nỗi này! Nỡ để con, rày nhớ mai mong, nước mắt chảy hai hàng, đầy một mẻ.",
        "",
        "Nay vừa chế phục sẵn rồi; bày đặt tang nghi theo lệ.",
        "Gậy khăn tuân cứ lối thường;",
        "Thành phục kính dâng tiền tế.",
        "",
        "Thương ôi!",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!"
      ]
    },
    {
      id: "le-chuc-thuc",
      title: "Văn khấn lễ Chúc Thực (dâng cơm khi còn linh cữu)",
      category: "tang-le",
      description: "Văn khấn lễ Chúc Thực – dâng cơm cho vong linh khi linh cữu còn quàn tại gia.",
      occasion: "Các bữa cơm dâng trước linh cữu trong những ngày để tang tại nhà",
      difficulty: "Khó",
      duration: "10-15 phút",
      preparation: [
        "Mâm cơm đơn giản hoặc đầy đủ (tùy bữa)",
        "Hương, nước, đũa bát cho vong linh",
        "Có thể thêm hoa quả, trầu cau"
      ],
      notes: [
        "Thường ngày nào cũng dâng cơm cho tới khi đưa tang, hạ huyệt",
        "Có thể đọc rút gọn một phần bài khấn cho phù hợp",
        "Vẫn để con cháu chủ lễ, thể hiện hiếu đạo"
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Đức Đương cảnh Thành hoàng chư vị Đại Vương.",
        "- Con kính lạy ngài Đông Trù Tư mệnh Táo phủ Thần quân.",
        "- Con kính lạy chư gia tiên Cao Tằng Tổ Khảo, Cao Tằng Tổ Tỷ họ……….",
        "",
        "Hôm nay là ngày…. Tháng…. Năm……",
        "Con trai trưởng (hoặc cháu đích tôn) là……… vâng theo lệnh của mẫu thân (hoặc phụ thân) và các chú bác, cùng với anh rể, chị gái và các em trai gái dâu rể, con cháu nội ngoại kính lạy.",
        "",
        "Nay nhân lễ Chúc Thực theo nghi lễ cổ truyền, kính dâng lễ mọn biểu lộ lòng thành,",
        "",
        "Trước linh vị của: Hiển… chân linh, xin kính cẩn trình thưa rằng:",
        "",
        "Thiết nghĩ! Nhân sinh tại thế,",
        "Họa mấy người sống tám, chín mươi,",
        "Đôi ba mươi năm cũng kể một đời.",
        "Song vận số biết làm sao tránh được.",
        "",
        "Nhớ hồn thuở trước: trong buổi xuân xanh,",
        "Ơn mẹ cha đạo cả sinh thành, đêm ngày dạy dỗ:",
        "Đường ăn, nỗi ở, việc cửa việc nhà,",
        "Lại lo bề nghi thất, nghi gia,",
        "Cho sum họp trúc, mai mấy đóa.",
        "",
        "… (có thể đọc đầy đủ như nguyên văn bạn đã chép nếu muốn trọn bài) …",
        "",
        "Cầu anh linh phù hộ cháu con,",
        "Cầu Thần Phật độ trì, cho vong hồn siêu thoát…",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!"
      ]
    },
    {
      id: "cao-long-than-tho-dia-tang",
      title: "Văn khấn Lễ cáo Long Thần Thổ Địa trước khi đào huyệt",
      category: "tang-le",
      description: "Văn khấn cáo Long Thần Thổ Địa trước khi đào huyệt để an táng người mất.",
      occasion: "Trước khi đào huyệt, cải táng, sang cát…",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      preparation: [
        "Hương, hoa",
        "Trầu cau",
        "Tiền vàng",
        "Rượu, nước, lễ mặn đơn giản"
      ],
      notes: [
        "Cúng tại vị trí huyệt mộ hoặc nơi đất chuẩn bị an táng",
        "Đọc trước khi cho thợ đào huyệt",
        "Có thể dùng chung cho các lễ cải táng, sang cát, di dời mộ"
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Phật, Chư Phật mười phương.",
        "- Con kính lạy Bản cảnh Hậu Thổ Thần chư vị.",
        "",
        "Tang chủ là: .......................................................",
        "Ngụ tại:…………….",
        "",
        "Hôm nay là ngày … tháng…. Năm……, gia đình có táng cố phụ (hay cố mẫu) là họ………… húy hiệu…….., tiền tước là….., thọ chung ngày …. ở khu đất này, kính dâng lễ vật…….. lễ nghi các thứ.",
        "",
        "Thiết nghĩ:",
        "Đất có dữ lành,",
        "Đều do họa phúc,",
        "Kết phát dựa vào âm đức,",
        "Cũng nhờ Thần lực hiển linh.",
        "Ấy thực thường tình,",
        "Xiết bao cảm cách.",
        "",
        "Những mong mồ yên mả đẹp,",
        "Vậy dâng lễ bạc tâm thành,",
        "Nhờ ơn Đại đức,",
        "Thấu nỗi u tình,",
        "Khiến cho vong linh,",
        "Được yên nơi chín suối,",
        "Phù hộ dương trần con cháu nội, ngoại bình yên.",
        "",
        "Chúng con lễ bạc tâm thành cúi xin được phù hộ độ trì.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!"
      ]
    },
  ],
  "khai-truong": [
    {
      id: "van-khan-tan-gia-gia-tien",
      title: "Văn cúng gia tiên nhân lễ Tân gia",
      category: "tan-gia",
      description: "Văn khấn cáo yết gia tiên khi dọn về nhà mới, lập bàn thờ và làm lễ Tân gia.",
      occasion: "Lễ Tân gia, nhập trạch về nhà mới",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      preparation: [
        "Mâm cơm mặn hoặc chay tùy tâm",
        "Hương, hoa, trầu cau",
        "Rượu, nước, hoa quả",
        "Vàng mã cúng gia tiên"
      ],
      notes: [
        "Thường kết hợp với lễ nhập trạch, cáo yết Thần linh Thổ địa trước",
        "Sau khi an vị bát hương, mới tiến hành khấn gia tiên",
        "Đọc rõ địa chỉ nhà mới trong bài khấn"
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "",
        "Tín chủ (chúng) con là:.................",
        "Hôm nay là ngày….. tháng...... năm....., tín chủ con cùng gia đình mới dọn đến đây, tại: (địa chỉ) ..........",
        "",
        "Tín chủ con thiết lập linh sàng, sắp sửa lễ vật, bày trên bàn thờ, trước linh tọa kính trình các Cụ nội ngoại Gia tiên Tiền tổ.",
        "",
        "Nhờ hồng phúc Tổ tiên, ông bà cha mẹ, chúng con đã tạo lập được ngôi nhà mới, thiết lập hương án thờ, kê giường nhóm lửa kính lễ khánh hạ.",
        "",
        "Nay chúng con làm lễ Tân gia, cúi xin các cụ, ông bà cùng chư vị Hương linh nội ngoại thương xót con cháu, chứng giám lòng thành, thụ hưởng lễ vật, phù hộ độ trì cho chúng con: lộc tài vượng tiến, gia đạo hưng long, cháu con được bình an mạnh khoẻ.",
        "",
        "Chúng con lễ bạc tâm thành, trước án kính lễ, cúi xin được phù hộ độ trì.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!"
      ]
    },
  ],
  "tho-dia": [
    {
      id: "thanh-minh-am-phan-long-mach",
      title: "Văn khấn lễ âm phần Long Mạch, Sơn thần Thổ phủ nơi mộ",
      category: "thanh-minh",
      description:
        "Văn khấn Thần linh Long Mạch, Sơn thần Thổ phủ khi tảo mộ, sửa sang mộ phần.",
      occasion: "Tiết Thanh Minh hoặc khi tảo mộ, sửa mộ, bốc mộ",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      preparation: [
        "Hương, đèn",
        "Trầu cau",
        "Tiền vàng",
        "Rượu thịt (chân giò, gà luộc hoặc giò nạc)",
        "Hoa quả",
      ],
      notes: [
        "Đặt lễ tại chỗ thờ chung hoặc miếu/thần linh trong nghĩa trang",
        "Khấn Thần linh trước rồi mới ra từng phần mộ khấn vong linh",
        "Có thể dùng cho các dịp khác ngoài Thanh Minh khi sửa sang mộ",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Hoàng thiên Hậu Thổ, chư vị Tôn thần.",
        "- Con kính lạy các ngài Thần linh bản xứ cai quản trong khu vực này.",
        "",
        "Hôm nay là ngày: .........................................................",
        "Tín chủ (chúng) con là:..............................................",
        "",
        "Nhân tiết Thanh minh (hoặc là nhân tiết thu, tiết đông, hoặc nhân ngày lành tháng tốt…) tín chủ con thành tâm sắm lễ, quả cau lá trầu, hương hoa trà quả, thắp nén tâm hương kính dâng trước án, kính mời chư vị Tôn thần lai lâm chiếu giám.",
        "",
        "Gia đình chúng con có ngôi mộ của......................., táng tại xứ này, nay muốn sửa sang xây đắp (hoặc tảo mộ, bốc mộ…). Vì vậy chúng con xin kính cáo các đấng Thần linh, Thổ công, Thổ phủ Long Mạch, Tiền Chu Tước, Hậu Huyền Vũ, Tả Thanh Long, Hữu Bạch Hổ và Chư vị Tôn thần cai quản trong khu vực này.",
        "",
        "Chúng con kính mời các vị chư Thần về đây chứng giám lòng thành, thụ hưởng lễ vật, độ cho vong linh được an nhàn yên ổn, siêu thoát. Cúi xin các vị phù hộ độ trì cho tín chủ chúng con toàn gia mạnh khỏe an bình, bốn mùa không tật ách, tám tiết hưởng thái bình.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
    {
      id: "thanh-minh-vong-linh-ngoai-mo",
      title: "Văn khấn lễ vong linh ngoài mộ",
      category: "thanh-minh",
      description:
        "Văn khấn trực tiếp với vong linh tại phần mộ khi tảo mộ, sửa sang, bồi thổ.",
      occasion: "Tiết Thanh Minh hoặc khi viếng, sửa, cải táng mộ phần",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      preparation: [
        "Hương, hoa",
        "Trầu cau",
        "Tiền vàng",
        "Trà, rượu, hoa quả",
      ],
      notes: [
        "Đứng trước từng phần mộ để khấn riêng",
        "Có thể thêm thông tin cụ thể: Hiển khảo, Hiển tỷ, Tổ khảo, Tổ tỷ…",
        "Nên kết hợp dọn dẹp, sửa sang mộ trước khi khấn",
      ],
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "- Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "- Con kính lạy Hương linh……………… (Hiển khảo, Hiển tỷ hoặc Tổ Khảo………….).",
        "",
        "Hôm nay là ngày. . ………….",
        "Nhân tiết:…………………………. ",
        "Tín chủ (chúng) con: ........................................",
        "Ngụ tại:…………………….",
        "",
        "Chúng con và toàn thể gia đình con cháu, nhờ công ơn võng cực, nền đức cao dầy, gây dựng cơ nghiệp của………….. chạnh lòng nghĩ đến âm phần ở nơi hoang vắng, tín chủ con thành tâm sắm lễ, quả cau lá trầu, hương hoa trà quả, thắp nén tâm hương kính dâng trước mộ, kính mời chân linh....... . .. ........ . .... . . .lai lâm hiến hưởng.",
        "",
        "Chúng con xin phép được sửa sang phần mộ, bồi sa, bồi thổ, cho được dầy bền, tu sửa minh đường hậu quỷ cho thêm vững chắc.",
        "",
        "Nhờ ơn Phật Thánh phù trì, đội đức trời che đất chở, cảm niệm Thần linh phù độ, khiến cho được chữ bình an, âm siêu dương thái.",
        "",
        "Con cháu chúng con xin vì chân linh . . ........ phát nguyện tích đức tu nhân, làm duyên, làm phúc cúng dâng Tam Bảo, giúp đỡ cô nhi quả phụ, tế bần cứu nạn, hiếu thuận tông nhân để lấy phúc này hướng về Tiên Tổ.",
        "",
        "Cúi xin linh thiêng chứng giám, thụ hưởng lễ vật, phù hộ độ trì con cháu, qua lại soi xét cửa nhà. Che tai cứu nạn, ban tài tiếp lộc, điều lành mang đến, điều dữ xua đi. Độ cho gia đạo hưng long, quế hở tươi tốt, cháu con vinh hưởng lộc trời, già trẻ nhuần ơn Phật Thánh.",
        "",
        "Chúng con lễ bạc tâm thành, cúi xin chứng giám.",
        "",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
    },
  ],
  "nam-moi": [
    {
      id: "ha-nguyen-com-moi",
      title: "Văn khấn Tết Hạ Nguyên - Tết Cơm mới",
      category: "nam-moi",
      description:
        "Văn khấn tổ tiên ngày Tết Cơm Mới (Tết Hạ Nguyên), tiến tân cơm gạo mới cúng tổ tiên",
      occasion: "Mồng 1, mồng 10 hoặc Rằm tháng 10 Âm lịch",
      difficulty: "Trung bình",
      duration: "15-20 phút",
      content: [
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
        "",
        "Con lạy chín phương Trời, mười phương Chư Phật, Chư Phật mười phương.",
        "Con kính lạy Hoàng thiên Hậu Thổ chư vị Tôn thần.",
        "Con kính lạy ngài Bản cảnh Thành hoàng, ngài Bản xứ thổ địa, ngài Bản gia Táo quân cùng chư vị Tôn thần.",
        "Con kính lạy Cao Tằng Tổ khảo, Cao Tằng Tổ Tỷ, Thúc Bá, Đệ Huynh, Cô Di, Tỷ Muội họ nội họ ngoại.",
        "",
        "Tín chủ (chúng) con là:.............................................",
        "Ngụ tại:......................................................................",
        "",
        "Hôm nay là ngày mồng Một (mồng Mười, Rằm) tháng Mười là ngày Tết Cơm Mới, tín chủ con thành tâm sắm lễ, quả cau lá trầu, hương hoa trà quả, nấu cơm gạo mới, thắp nén tâm hương dâng lên trước án.",
        "",
        "Trộm nghĩ rằng:",
        "Cây cao bóng mát",
        "Quả tốt hương bay",
        "Công tài bồi xưa những ai gây",
        "Của quí hoá nay con cháu hưởng",
        "Ơn Trời Đất Phật Tiên, Chư vị Tôn thần",
        "Sau nhờ ơn Tổ tiên gây dựng, kể công tân khổ biết là bao",
        "Đến nay con cháu dồi dào, hưởng miếng trân cam",
        "",
        "Nay nhân mùa gặt hái",
        "Gánh nếp tẻ đầu mùa",
        "Nghĩ đến ơn xưa",
        "Cày bừa vun xới,",
        "Sửa nồi cơm mới",
        "Kính cẩn dâng lên",
        "Thường tiên nếm trước",
        "Mong nhờ Tổ phước",
        "Hoà cốc phong đăng",
        "Thóc lúa thêm tăng",
        "Hoa màu tươi mới",
        "Làm ăn tiến tới",
        "Con cháu được nhờ",
        "Lễ tuy đơn sơ",
        "Tỏ lòng thành kính",
        "",
        "Chúng con kính mời ngài Bản cảnh Thành hoàng Chư vị Đại Vương, ngài Bản xứ Thần linh Thổ địa, ngài Bản gia Táo quân, Ngũ phương, Long Mạch, Tài thần. Cúi xin các Ngài giáng lâm trước án chứng giám lòng thành thụ hưởng lễ vật.",
        "",
        "Chúng con kính mời các cụ Tổ khảo, Tổ Tỷ, chư vị Hương linh gia tiên nội ngoại họ..............., cúi xin thương xót con cháu linh thiêng hiện về chứng giám tâm thành thụ hưởng lễ vật.",
        "",
        "Chúng con lễ bạc tâm thành, trước án kính lễ, cúi xin được phù hộ độ trì.",
        "",
        "Nam mô a di Đà Phật",
        "Nam mô a di Đà Phật!",
        "Nam mô a di Đà Phật!",
      ],
      preparation: [
        "Lễ chính: Hương hoa, đèn nến, hoa quả, trầu cau, trà, rượu",
        "Cơm gạo mới: Xôi gạo nếp mới hoặc cơm gạo tẻ mới",
        "Lễ mặn: Thịt gà, thịt lợn luộc, cá, các món ăn thơm ngon tinh khiết",
        "Đặc sản: Gạo nếp mới, các sản vật đầu mùa Thu Đông",
      ],
      notes: [
        "Tết Hạ Nguyên được tiến hành vào ngày mồng 1, mồng 10 hoặc Rằm tháng 10 Âm lịch",
        "Ngày này Thiên Đình cử thần Tam Thanh xuống trần gian xem xét việc tốt xấu",
        "Là dịp 'tiến tân' cơm gạo mới cúng tổ tiên sau mùa gặt",
        "Nên mua quà và gạo nếp mới biếu ông bà, cha mẹ để tỏ lòng hiếu thuận",
        "Cần điền đầy đủ tên tín chủ và địa chỉ cụ thể vào chỗ trống",
        "Lễ vật cần tinh khiết, thể hiện lòng biết ơn công lao tổ tiên gây dựng",
      ],
    },
  ],
};

export function getPrayersByCategory(categoryId: string): Prayer[] {
  return prayersData[categoryId] || [];
}

export function getPrayerById(
  categoryId: string,
  prayerId: string
): Prayer | undefined {
  const prayers = prayersData[categoryId] || [];
  return prayers.find((p) => p.id === prayerId);
}

export const categoryInfo: Record<
  string,
  { title: string; description: string; image: string; color: string }
> = {
  featured: {
    title: "Văn khấn khác",
    description: "Những bài văn khấn phổ biến và hay được sử dụng nhất",
    image: "/prayers/featured.jpg",
    color: "from-wine-red/20 to-gold/20",
  },
  tet: {
    title: "Văn khấn Tết",
    description: "Văn khấn cho dịp Tết Nguyên Đán",
    image: "/prayers/tet.jpg",
    color: "from-rose-100 to-red-100",
  },
  ram: {
    title: "Văn khấn Rằm",
    description: "Văn khấn mồng 1, rằm hàng tháng",
    image: "/prayers/ram.jpg",
    color: "from-amber-100 to-yellow-100",
  },
  "gia-tien": {
    title: "Cúng gia tiên",
    description: "Văn khấn cúng tổ tiên, cúng giỗ",
    image: "/prayers/gia-tien.jpg",
    color: "from-purple-100 to-pink-100",
  },
  "khai-truong": {
    title: "Khai trương",
    description: "Văn khấn khai trương, khởi công",
    image: "/prayers/khai-truong.jpg",
    color: "from-green-100 to-emerald-100",
  },
  "tho-dia": {
    title: "Thổ địa - Thần tài",
    description: "Văn khấn cúng thổ địa, thần tài",
    image: "/prayers/tho-dia.jpg",
    color: "from-blue-100 to-cyan-100",
  },
  "nam-moi": {
    title: "Cúng đầu năm",
    description: "Văn khấn đầu năm, cúng giao thừa",
    image: "/prayers/nam-moi.jpg",
    color: "from-orange-100 to-amber-100",
  },
};
