// Mock data cho các loại văn khấn
export interface Prayer {
  id: string
  title: string
  category: string
  description: string
  occasion: string
  difficulty: "Dễ" | "Trung bình" | "Khó"
  duration: string
  content: string[]
  preparation: string[]
  notes: string[]
}

export const prayersData: Record<string, Prayer[]> = {
  featured: [
    {
      id: "van-khan-ram-thang",
      title: "Văn khấn rằm tháng",
      category: "featured",
      description: "Bài văn khấn ngắn gọn, dễ nhớ dùng cho mồng 1, rằm hàng tháng",
      occasion: "Mồng 1, Rằm",
      difficulty: "Dễ",
      duration: "5-7 phút",
      content: [
        "Nam mô A Di Đà Phật",
        "Kính lạy Chư Phật, Chư Tổ, Chư Tiên, Chư Thánh",
        "Con (tên), sinh năm (năm sinh), quê quán (quê quán)",
        "Hôm nay, ngày (ngày/tháng/năm âm lịch)",
        "Con cùng gia đình kính dâng hương hoa, trà quả",
        "Lễ bái Chư Phật, Chư Tổ, Chư Tiên, Chư Thánh",
        "Cầu mong gia đình luôn bình an, sức khỏe",
        "Công việc làm ăn hanh thông, thuận lợi",
        "Con cái học hành tấn tới, tiến bộ",
        "Xin Chư Phật, Chư Tổ độ trì, phù hộ",
        "Con thành tâm cúi đầu lạy tạ",
        "Nam mô A Di Đà Phật (3 lần)",
      ],
      preparation: [
        "Hương (3 hoặc 5 nén)",
        "Hoa quả tươi (5 loại)",
        "Trà hoặc nước lọc",
        "Bánh kẹo (tùy ý)",
        "Tâm thành kính",
      ],
      notes: [
        "Nên đọc vào buổi sáng sớm hoặc trưa",
        "Tắm rửa sạch sẽ trước khi cúng",
        "Tập trung, không nói chuyện trong khi đọc",
        "Có thể điều chỉnh tên, năm sinh cho phù hợp",
      ],
    },
    {
      id: "van-khan-gia-tien",
      title: "Văn khấn cúng gia tiên",
      category: "featured",
      description: "Bài văn khấn cúng tổ tiên, ông bà, cha mẹ đã khuất",
      occasion: "Ngày giỗ, Rằm, Tết",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      content: [
        "Nam mô A Di Đà Phật",
        "Kính lạy Chư Phật, Chư Bồ Tát",
        "Kính lạy hương linh Ông Bà Tổ Tiên",
        "Con (tên), sinh năm (năm sinh)",
        "Là con cháu đời thứ (số) của dòng họ (họ)",
        "Hôm nay, ngày (ngày giỗ/rằm/tết)",
        "Con cùng gia đình kính dâng hương hoa, trà quả",
        "Lễ bái hương linh Ông Bà Tổ Tiên",
        "Tưởng nhớ công ơn sinh thành, dưỡng dục",
        "Cầu mong Ông Bà được siêu sinh lạc quốc",
        "Phù hộ cho con cháu luôn bình an",
        "Gia đình êm ấm, sum vầy",
        "Con xin thành tâm cúi đầu lạy tạ",
        "Nam mô A Di Đà Phật (3 lần)",
      ],
      preparation: [
        "Mâm cơm (5 bát cơm, rượu, canh, thịt, rau)",
        "Hương (1 bó hoặc 9 nén)",
        "Hoa quả (5 loại)",
        "Bánh kẹo, trà",
        "Vàng mã (tùy điều kiện)",
        "Tâm thành kính nhớ đến ông bà",
      ],
      notes: [
        "Nên cúng vào giờ Tỵ (11h-13h) hoặc giờ Mùi (13h-15h)",
        "Chuẩn bị mâm cơm chu đáo, sạch sẽ",
        "Cả nhà cùng tham gia để thể hiện lòng hiếu thảo",
        "Sau khi cúng, gia đình cùng dùng cơm",
      ],
    },
  ],
  tet: [
    {
      id: "van-khan-giao-thua",
      title: "Văn khấn giao thừa",
      category: "tet",
      description: "Bài văn khấn đón giao thừa, tiễn năm cũ đón năm mới",
      occasion: "Đêm 30 Tết",
      difficulty: "Trung bình",
      duration: "15-20 phút",
      content: [
        "Nam mô A Di Đà Phật",
        "Kính lạy Chư Phật, Chư Bồ Tát Ma Ha Tát",
        "Kính lạy Ngọc Hoàng Thượng Đế",
        "Kính lạy Ông Bà Tổ Tiên",
        "Con (tên), sinh năm (năm sinh), quê quán (quê quán)",
        "Hôm nay, đêm giao thừa, tiễn năm (tên năm cũ)",
        "Đón năm mới (tên năm mới)",
        "Con cùng gia đình kính dâng lễ vật",
        "Cúng Chư Phật, Chư Thánh, Ông Bà Tổ Tiên",
        "Tạ ơn một năm qua luôn phù hộ độ trì",
        "Gia đình được bình an, sức khỏe",
        "Cầu mong năm mới an khang, thịnh vượng",
        "Vạn sự như ý, tài lộc đầy nhà",
        "Con xin thành tâm cúi đầu lạy tạ",
        "Nam mô A Di Đà Phật (3 lần)",
      ],
      preparation: [
        "Mâm cỗ đầy đủ (gà, giò, chả, bánh chưng)",
        "Hương (1-2 bó)",
        "Hoa tươi, quả ngũ quả",
        "Bánh mứt Tết",
        "Rượu trắng hoặc rượu nếp",
        "Vàng mã đầy đủ",
      ],
      notes: [
        "Cúng vào 23h-0h đêm giao thừa",
        "Cả nhà tập trung, không ồn ào",
        "Sau khi cúng xong mới được đi chúc Tết",
        "Giữ nguyên mâm cỗ đến sáng mùng 1",
      ],
    },
    {
      id: "van-khan-mung-1-tet",
      title: "Văn khấn mùng 1 Tết",
      category: "tet",
      description: "Bài văn khấn ngày đầu năm, cầu may mắn cho cả năm",
      occasion: "Mùng 1 Tết",
      difficulty: "Dễ",
      duration: "8-10 phút",
      content: [
        "Nam mô A Di Đà Phật",
        "Kính lạy Chư Phật, Chư Bồ Tát",
        "Kính lạy Ông Bà Tổ Tiên",
        "Con (tên), sinh năm (năm sinh)",
        "Hôm nay, mùng 1 Tết năm (tên năm)",
        "Con cùng gia đình kính dâng hương hoa",
        "Lễ bái Chư Phật, Ông Bà Tổ Tiên",
        "Cầu chúc năm mới vạn sự hanh thông",
        "Gia đạo bình an, sức khỏe dồi dào",
        "Công danh thành đạt, tài lộc dư dả",
        "Con cái ngoan ngoãn, học hành tấn tới",
        "Con xin thành tâm cúi đầu lạy tạ",
        "Nam mô A Di Đà Phật (3 lần)",
      ],
      preparation: [
        "Hương (3-5 nén)",
        "Hoa quả tươi",
        "Bánh mứt Tết",
        "Trà, nước ngọt",
        "Tâm hoan hỷ đón năm mới",
      ],
      notes: [
        "Cúng vào sáng sớm mùng 1",
        "Mặc quần áo đẹp, sạch sẽ",
        "Nói năng cẩn thận, tránh điều xui xẻo",
        "Sau khi cúng, đi chúc Tết người lớn tuổi",
      ],
    },
  ],
  ram: [
    {
      id: "van-khan-mong-1",
      title: "Văn khấn mồng 1 âm lịch",
      category: "ram",
      description: "Bài văn khấn đầu tháng âm lịch",
      occasion: "Mồng 1 hàng tháng",
      difficulty: "Dễ",
      duration: "5-7 phút",
      content: [
        "Nam mô A Di Đà Phật",
        "Kính lạy Chư Phật, Chư Bồ Tát",
        "Con (tên), sinh năm (năm sinh)",
        "Hôm nay, mồng 1 tháng (tháng) năm (năm)",
        "Con kính dâng hương hoa, trà quả",
        "Lễ bái Chư Phật, Chư Tổ",
        "Cầu mong tháng mới bình an, may mắn",
        "Công việc thuận lợi, sức khỏe dồi dào",
        "Con xin thành tâm cúi đầu lạy tạ",
        "Nam mô A Di Đà Phật (3 lần)",
      ],
      preparation: ["Hương (3 nén)", "Hoa quả", "Trà hoặc nước", "Tâm thành kính"],
      notes: [
        "Cúng sáng sớm hoặc trưa",
        "Không cần mâm cỗ phức tạp",
        "Tập trung, chân thành khi đọc",
      ],
    },
  ],
  "gia-tien": [
    {
      id: "van-khan-gio-to",
      title: "Văn khấn ngày giỗ",
      category: "gia-tien",
      description: "Bài văn khấn dùng trong ngày giỗ ông bà, cha mẹ",
      occasion: "Ngày giỗ",
      difficulty: "Trung bình",
      duration: "15-20 phút",
      content: [
        "Nam mô A Di Đà Phật",
        "Kính lạy Chư Phật, Chư Bồ Tát Ma Ha Tát",
        "Kính lạy hương linh (tên người quá cố)",
        "Con là (tên), sinh năm (năm sinh)",
        "Hôm nay, nhằm ngày (ngày giỗ)",
        "Là ngày kỵ của (Ông/Bà/Cha/Mẹ)",
        "Con cùng gia đình kính dâng lễ vật",
        "Cơm canh, rượu thịt, hương hoa trà quả",
        "Tưởng nhớ công ơn sinh thành, dưỡng dục",
        "Mong hương linh được siêu thoát, an lạc",
        "Phù hộ con cháu luôn bình an, khỏe mạnh",
        "Con xin thành tâm cúi đầu lạy tạ",
        "Nam mô A Di Đà Phật (3 lần)",
      ],
      preparation: [
        "Mâm cơm đầy đủ",
        "Hương (1 bó)",
        "Hoa quả (5 loại)",
        "Rượu, trà",
        "Vàng mã",
        "Tâm nhớ về người đã khuất",
      ],
      notes: [
        "Cúng vào giờ Ngọ (11h-13h)",
        "Chuẩn bị chu đáo, sạch sẽ",
        "Cả nhà cùng tham dự",
        "Sau khi cúng, cùng dùng cơm",
      ],
    },
  ],
  "khai-truong": [
    {
      id: "van-khan-khai-truong-cua-hang",
      title: "Văn khấn khai trương cửa hàng",
      category: "khai-truong",
      description: "Bài văn khấn dùng trong lễ khai trương, mở cửa hàng mới",
      occasion: "Khai trương",
      difficulty: "Trung bình",
      duration: "10-15 phút",
      content: [
        "Nam mô A Di Đà Phật",
        "Kính lạy Chư Phật, Chư Bồ Tát",
        "Kính lạy Thần Tài, Thổ Địa",
        "Con (tên), sinh năm (năm sinh)",
        "Hôm nay, ngày (ngày/tháng/năm)",
        "Con khai trương cửa hàng (tên cửa hàng)",
        "Tại địa chỉ (địa chỉ)",
        "Con kính dâng lễ vật, hương hoa",
        "Lễ bái Chư Phật, Thần Tài, Thổ Địa",
        "Cầu mong khai trương đại cát, đại lợi",
        "Khách hàng đông đúc, mua bán hanh thông",
        "Tài lộc tấn tới, vạn sự như ý",
        "Con xin thành tâm cúi đầu lạy tạ",
        "Nam mô A Di Đà Phật (3 lần)",
      ],
      preparation: [
        "Mâm cỗ khai trương (gà, heo, cá)",
        "Hương (1 bó)",
        "Hoa tươi",
        "Quả ngũ quả",
        "Rượu, trà",
        "Vàng mã",
        "Lộc khai trương (tiền lì xì)",
      ],
      notes: [
        "Chọn giờ tốt để khai trương",
        "Mời thầy cúng nếu có thể",
        "Chuẩn bị lộc phát cho khách",
        "Trang trí cửa hàng đẹp, rực rỡ",
      ],
    },
  ],
  "tho-dia": [
    {
      id: "van-khan-tho-dia",
      title: "Văn khấn Thổ Địa",
      category: "tho-dia",
      description: "Bài văn khấn cúng Thổ Địa, Thần Tài mồng 1, rằm",
      occasion: "Mồng 1, Rằm, Mùng 2 tháng 2",
      difficulty: "Dễ",
      duration: "5-8 phút",
      content: [
        "Nam mô A Di Đà Phật",
        "Kính lạy Thổ Địa Công Công",
        "Kính lạy Thần Tài, Thần Lộc",
        "Con (tên), sinh năm (năm sinh)",
        "Đang sinh sống tại (địa chỉ)",
        "Hôm nay, ngày (ngày/tháng/năm)",
        "Con kính dâng hương hoa, trà quả",
        "Lễ bái Thổ Địa, Thần Tài",
        "Cầu mong trấn ấp nhà cửa",
        "Gia đình bình an, tài lộc hanh thông",
        "Làm ăn buôn bán thuận lợi",
        "Con xin thành tâm cúi đầu lạy tạ",
        "Nam mô A Di Đà Phật (3 lần)",
      ],
      preparation: [
        "Hương (3-5 nén)",
        "Hoa quả",
        "Trà, rượu trắng",
        "Bánh kẹo (tùy ý)",
        "Vàng mã nhỏ",
      ],
      notes: [
        "Cúng tại bàn thờ Thổ Địa hoặc sân nhà",
        "Có thể cúng cùng lúc với cúng rằm",
        "Mùng 2/2 âm lịch là ngày Thổ Địa",
      ],
    },
  ],
  "nam-moi": [
    {
      id: "van-khan-dau-nam",
      title: "Văn khấn đầu năm",
      category: "nam-moi",
      description: "Bài văn khấn mùng 1 Tết, cầu may cho cả năm",
      occasion: "Mùng 1 Tết",
      difficulty: "Dễ",
      duration: "8-10 phút",
      content: [
        "Nam mô A Di Đà Phật",
        "Kính lạy Chư Phật, Chư Bồ Tát",
        "Kính lạy Ông Bà Tổ Tiên",
        "Con (tên), sinh năm (năm sinh)",
        "Hôm nay, mùng 1 Tết năm (năm mới)",
        "Con cùng gia đình kính dâng lễ vật",
        "Lễ bái Chư Phật, Ông Bà Tổ Tiên",
        "Cầu chúc năm mới an khang, thịnh vượng",
        "Vạn sự như ý, tài lộc dồi dào",
        "Gia đình sum vầy, hạnh phúc",
        "Con xin thành tâm cúi đầu lạy tạ",
        "Nam mô A Di Đà Phật (3 lần)",
      ],
      preparation: ["Hương (3-5 nén)", "Hoa quả tươi", "Bánh mứt Tết", "Trà, nước ngọt"],
      notes: [
        "Cúng sáng sớm mùng 1",
        "Mặc đồ đẹp, sạch sẽ",
        "Tâm hồn vui vẻ, tích cực",
      ],
    },
  ],
}

export function getPrayersByCategory(categoryId: string): Prayer[] {
  return prayersData[categoryId] || []
}

export function getPrayerById(categoryId: string, prayerId: string): Prayer | undefined {
  const prayers = prayersData[categoryId] || []
  return prayers.find((p) => p.id === prayerId)
}

export const categoryInfo: Record<
  string,
  { title: string; description: string; icon: string; color: string }
> = {
  featured: {
    title: "Văn khấn được ghim",
    description: "Những bài văn khấn phổ biến và hay được sử dụng nhất",
    icon: "📌",
    color: "from-wine-red/20 to-gold/20",
  },
  tet: {
    title: "Văn khấn Tết",
    description: "Văn khấn cho dịp Tết Nguyên Đán",
    icon: "🎊",
    color: "from-rose-100 to-red-100",
  },
  ram: {
    title: "Văn khấn Rằm",
    description: "Văn khấn mồng 1, rằm hàng tháng",
    icon: "🌕",
    color: "from-amber-100 to-yellow-100",
  },
  "gia-tien": {
    title: "Cúng gia tiên",
    description: "Văn khấn cúng tổ tiên, cúng giỗ",
    icon: "🙏",
    color: "from-purple-100 to-pink-100",
  },
  "khai-truong": {
    title: "Khai trương",
    description: "Văn khấn khai trương, khởi công",
    icon: "🏪",
    color: "from-green-100 to-emerald-100",
  },
  "tho-dia": {
    title: "Thổ địa - Thần tài",
    description: "Văn khấn cúng thổ địa, thần tài",
    icon: "🏠",
    color: "from-blue-100 to-cyan-100",
  },
  "nam-moi": {
    title: "Cúng đầu năm",
    description: "Văn khấn đầu năm, cúng giao thừa",
    icon: "🎆",
    color: "from-orange-100 to-amber-100",
  },
}
